INSERT INTO `skill` (`name`) VALUES ('Java');
INSERT INTO `skill` (`name`) VALUES ('Spring');
INSERT INTO `skill` (`name`) VALUES ('Spring Boot');
INSERT INTO `skill` (`name`) VALUES ('Spring Data JPA');
INSERT INTO `skill` (`name`) VALUES ('Spring Security');
INSERT INTO `skill` (`name`) VALUES ('Spring HATEOAS');
INSERT INTO `skill` (`name`) VALUES ('Hibernate');
INSERT INTO `skill` (`name`) VALUES ('JPA');
INSERT INTO `skill` (`name`) VALUES ('Python');
INSERT INTO `skill` (`name`) VALUES ('Django');
INSERT INTO `skill` (`name`) VALUES ('Flask');
INSERT INTO `skill` (`name`) VALUES ('FastAPI');
INSERT INTO `skill` (`name`) VALUES ('JavaScript');
INSERT INTO `skill` (`name`) VALUES ('TypeScript');
INSERT INTO `skill` (`name`) VALUES ('React');
INSERT INTO `skill` (`name`) VALUES ('Angular');
INSERT INTO `skill` (`name`) VALUES ('Vue');
INSERT INTO `skill` (`name`) VALUES ('Node.js');
INSERT INTO `skill` (`name`) VALUES ('Express');
INSERT INTO `skill` (`name`) VALUES ('NestJS');
INSERT INTO `skill` (`name`) VALUES ('Go');
INSERT INTO `skill` (`name`) VALUES ('Rust');
INSERT INTO `skill` (`name`) VALUES ('C');
INSERT INTO `skill` (`name`) VALUES ('C++');
INSERT INTO `skill` (`name`) VALUES ('C#');
INSERT INTO `skill` (`name`) VALUES ('PHP');
INSERT INTO `skill` (`name`) VALUES ('Laravel');
INSERT INTO `skill` (`name`) VALUES ('Symfony');
INSERT INTO `skill` (`name`) VALUES ('Ruby');
INSERT INTO `skill` (`name`) VALUES ('Ruby on Rails');
INSERT INTO `skill` (`name`) VALUES ('Kotlin');
INSERT INTO `skill` (`name`) VALUES ('MySQL');
INSERT INTO `skill` (`name`) VALUES ('PostgreSQL');
INSERT INTO `skill` (`name`) VALUES ('MongoDB');
INSERT INTO `skill` (`name`) VALUES ('Redis');
INSERT INTO `skill` (`name`) VALUES ('Docker');
INSERT INTO `skill` (`name`) VALUES ('Kubernetes');
INSERT INTO `skill` (`name`) VALUES ('Terraform');
INSERT INTO `skill` (`name`) VALUES ('Git');
INSERT INTO `skill` (`name`) VALUES ('GitHub Actions');
INSERT INTO `skill` (`name`) VALUES ('Jenkins');
INSERT INTO `skill` (`name`) VALUES ('Travis CI');
INSERT INTO `skill` (`name`) VALUES ('CircleCI');
INSERT INTO `skill` (`name`) VALUES ('AWS');
INSERT INTO `skill` (`name`) VALUES ('Azure');
INSERT INTO `skill` (`name`) VALUES ('Google Cloud');
INSERT INTO `skill` (`name`) VALUES ('Heroku');
INSERT INTO `skill` (`name`) VALUES ('Netlify');
INSERT INTO `skill` (`name`) VALUES ('Vercel');
INSERT INTO `skill` (`name`) VALUES ('DigitalOcean');
INSERT INTO `skill` (`name`) VALUES ('Linux');
INSERT INTO `skill` (`name`) VALUES ('Windows');
INSERT INTO `skill` (`name`) VALUES ('MacOS');
INSERT INTO `skill` (`name`) VALUES ('Android');
INSERT INTO `skill` (`name`) VALUES ('iOS');
INSERT INTO `skill` (`name`) VALUES ('Flutter');
INSERT INTO `skill` (`name`) VALUES ('React Native');
INSERT INTO `skill` (`name`) VALUES ('S.O.L.I.D');
INSERT INTO `skill` (`name`) VALUES ('TDD');
INSERT INTO `skill` (`name`) VALUES ('BDD');
INSERT INTO `skill` (`name`) VALUES ('DDD');
INSERT INTO `skill` (`name`) VALUES ('CI/CD');
INSERT INTO `skill` (`name`) VALUES ('Scrum');
INSERT INTO `skill` (`name`) VALUES ('Kanban');
INSERT INTO `skill` (`name`) VALUES ('Clean Code');
INSERT INTO `skill` (`name`) VALUES ('Design Patterns');
INSERT INTO `skill` (`name`) VALUES ('Microservices');
INSERT INTO `skill` (`name`) VALUES ('REST');
INSERT INTO `skill` (`name`) VALUES ('GraphQL');
INSERT INTO `skill` (`name`) VALUES ('WebSockets');
INSERT INTO `skill` (`name`) VALUES ('JWT');
INSERT INTO `skill` (`name`) VALUES ('OAuth2');
INSERT INTO `skill` (`name`) VALUES ('Clean Architecture');
INSERT INTO `skill` (`name`) VALUES ('Event Sourcing');
INSERT INTO `skill` (`name`) VALUES ('CQRS');