INSERT INTO `skill` (`id`, `name`) VALUES (1, 'Java');
INSERT INTO `skill` (`id`, `name`) VALUES (2, 'Spring');
INSERT INTO `skill` (`id`, `name`) VALUES (3, 'Spring Boot');
INSERT INTO `skill` (`id`, `name`) VALUES (4, 'Spring Data JPA');
INSERT INTO `skill` (`id`, `name`) VALUES (5, 'Spring Security');
INSERT INTO `skill` (`id`, `name`) VALUES (6, 'Spring HATEOAS');
INSERT INTO `skill` (`id`, `name`) VALUES (7, 'Hibernate');
INSERT INTO `skill` (`id`, `name`) VALUES (8, 'JPA');
INSERT INTO `skill` (`id`, `name`) VALUES (9, 'Python');
INSERT INTO `skill` (`id`, `name`) VALUES (10, 'Django');